### ISSUE TITLE
Add current path to default path+filename

### ISSUE THREAD

**Issue by tofagerl** [dkundel/vscode-new-file#10]
So if you're in ~/dev/project/src/components, and you want to create a file, instead of getting `newFile.ts` in the box, you would get `~/dev/projects/src/components/newFile.ts`. 
First of all it makes it clearer where you're about to create a file, secondly it makes it easier to create files 'en masse' without moving around in the filesystem for each file you need to create.

**Comment by dkundel** [comment]
Hi @tofagerl,

This should be fixed with the latest release of `v2.0.0`. Let me know if you have any other issues. I'll be regularly maintaining this from now on :) Sorry for the inactive time.

Cheers,
Dominik
