### ISSUE TITLE
How to disable new files created relative to current file?

### ISSUE THREAD

**Issue by Treri** [dkundel/vscode-new-file#12]
I want to disable crreate new file relative to current file. I want to use absolute in my working directory. Can I have a option to disable or enable this?

In old versions, it works fine. But when I update vscode-new-file to new version, I can't know the current file sometimes.

Sublime text advanced-new-file create new file will relative to root path of directive not the current file.

Could you please implement sublime advanced-new-file 's `default_root` option, and set it default to the top directory?

**Comment by dkundel** [comment]
Hi @Treri,

I just launched `v2.0.0` that allows you now to fully configure this (either per project or for your whole editor). Here are all options:

```json
{
  "newFile.defaultBaseFileName": "newFile",
  "newFile.relativeTo": "file", // "root" or "project"
  "newFile.defaultFileExtension": ".ts",
  "newFile.rootDirectory": "~",
  "newFile.showFullPath": true
}
```

Cheers,
Dominik

**Comment by Treri** [comment]
🎉🎉🎉

Thanks very much!!
