### ISSUE TITLE
It does not create a file when there is no open editor window

### ISSUE THREAD

**Issue by ilog2000** [dkundel/vscode-new-file#13]
File is not created if there is no open editor window.

Steps to reproduce (I am using Windows 10):
1. Create empty directory 'test'
2. >cd test
3. >code .
4. Press Ctrl-Alt-N
5. Type in 'test.html' and press Enter
6. Nothing happens

**Comment by ilog2000** [comment]
Sorry, I did not check other issues. This is a duplicate of https://github.com/dkundel/vscode-new-file/issues/9

**Comment by ilog2000** [comment]
It is still not working in v2.0.0

**Comment by dkundel** [comment]
Check my comment in issue #9
