### ISSUE TITLE
New commits never released?

### ISSUE THREAD

**Issue by craigjennings11** [dkundel/vscode-new-file#14]
It looks like some changes were made to fix issues #8, #9, and #10 but were never released. When can we see this update drop? It contains functionality that better matches Sublime's plugin and would be very nice to have.

**Comment by dkundel** [comment]
Hey @craigjennings11, thanks for the reminder! With my job change and everything this kinda got lost. I finally found time to get everything updated and added a bunch of config options to it as part of that. Check out version `2.0.0` and let me know if there are any issues. I'll try to maintain this more regularly now 🎉
