### ISSUE TITLE
Pops up with absolute path selected - relative path doesn't work

### ISSUE THREAD

**Issue by kierenj** [dkundel/vscode-new-file#15]
Hi - I recently updated to the latest version.  Now, when I hit Ctrl+Alt+N, I get the popup, but I get an absolute path in the popup, and the whole path is selected.  If I enter just a filename, it fails with a permission error since it's trying to create it in the VS Code executable path.

Let me know if this is intended (I wouldn't guess so?) or if I can do anything to help diagnose.

Thank you for the great plugin!

**Comment by dkundel** [comment]
Hey @kierenj. This is intended. You can change this behavior in the settings. Just add an entry to your settings with: `"newFile.showFullPath": false` and it will not use absolute paths anymore. There were a lot of people asking for this feature.

Hope this helps!

**Comment by kierenj** [comment]
Thanks - works fine.  Happy to use the config, just confusing that someone would prefer to have to press, at a minimum, "End, Left, Ctrl+Shift+Left" to select a filename with this as the default.  I prefer the idea of "Ctrl+A" if I want to do an absolute path!  But no biggie.

**Comment by dkundel** [comment]
Unfortunately VS Code doesn't offer that option yet :/ I would love to have that.
