### ISSUE TITLE
Add autocompletion

### ISSUE THREAD

**Issue by perlun** [dkundel/vscode-new-file#16]
Thanks for a great extension!

A feature I've been missing since migrating over from Atom is what https://atom.io/packages/advanced-new-file has:

> Advanced New File is a package for helping Atom users to create new files and folders more easily. It supports create new files and directory tree by typing a relative path with bash-like autocomplete support.

The "bash-like autocomplete support" is really nice and helpful when typing the name. Could something like this be implemented in this extension? Is it doable?

**Comment by dogoku** [comment]
That's currently not possible, due to limitations with the input box.  See https://github.com/Microsoft/vscode/issues/426

**Comment by perlun** [comment]
OK, thanks anyway @dogoku
