### ISSUE TITLE
Feature: newFile.relativeTo: 'selectedTreeFolder'

### ISSUE THREAD

**Issue by patrickhulce** [dkundel/vscode-new-file#18]
It'd be awesome to be able to highlight a particular folder in the tree view and have the shortcut queue up a new file in the selected folder.

**Comment by dkundel** [comment]
I'm not sure if i fully understand this request. Can you give a bit more details on your idea?

**Comment by patrickhulce** [comment]
Sure @dkundel! Basically here's my desired flow.

Let's say I have a file `test/deeply/nested/file-test.js` currently open in my editor, I want to add a new file in another location like `test/fixtures/my-fixture.json`, I have the `test/fixtures` folder expanded and selected in my file explorer on the left-hand side, and the file explorer has focus (not the editor). I want my keyboard shortcut to default the path to the new file to `test/fixtures` rather than `test/deeply/nested`. Does that make sense?

**Comment by dkundel** [comment]
Sounds interesting. I currently can't find anything in the VS Code API that allows me to get that information of the selected folder though. Did you come across an API like that? Or any extension that does something along these lines?
I could probably add an entry to the right-click menu that has an activation point for the menu with this behavior. Does that sound useful to you?

**Comment by patrickhulce** [comment]
Yeah looks like it's an open issue :/ https://github.com/Microsoft/vscode/issues/3553
I'm mostly just trying to recreate a lot of the conveniences I had with Atom :) context menu support would be a great close second!

**Comment by dkundel** [comment]
Hey @patrickhulce I just shipped v3.0.0 that implements an explorer menu entry that allows you to create files relative to that folder or file regardless of your remaining config.

Let me know if this works for or if you want anything else :)

Cheers,
Dominik
