### ISSUE TITLE
UX Enhancement: preselect the filename in the dialog

### ISSUE THREAD

**Issue by patrickhulce** [dkundel/vscode-new-file#19]
Not sure if this is possible given VScode's API surface, but it'd be awesome to preselect just the filename (without folder structure in absolute mode) for editing :)

**Comment by dkundel** [comment]
Hey @patrickhulce,

I would really love that feature but unfortunately it's still not possible in the VS Code API as far as I know. But feel free to open an issue to them :)

**Comment by patrickhulce** [comment]
Aw, bummer, I will thanks!

**Comment by Telokis** [comment]
@dkundel It's possible! (And I was about to create an issue asking for this exact feature)

https://code.visualstudio.com/docs/extensionAPI/vscode-api#InputBoxOptions

I may try to make a PR if you let me a little more time! :p

(I use this extension a lot so I want it to be as perfect as possible)
