### ISSUE TITLE
Add file relative to current open file

### ISSUE THREAD

**Issue by moostad** [dkundel/vscode-new-file#2]
That would be great if we could add  file relative to current open file when some was open for example
 if I'm editing ```src/db/models/car.ts``` and adding ```people.ts``` created in  ```src/db/models/people.ts``` 
 if I'm editing ```src/db/models/car.ts``` and adding ```../config.ts``` created in  ```src/db/config.ts```
 if I'm editing ```src/db/models/car.ts``` and adding ```foo/bar.ts``` created in  ```src/db/foo/bar.ts```
and in case it's needed to make a file relative to the project folder just start path with ```/``` like ```/tsconfig.json```

**Comment by dkundel** [comment]
Good suggestion. I'm currently busy with relocating and switching jobs. I can cover this in April :) If you want to do it in the meantime, feel free to send a PR

**Comment by dkundel** [comment]
I pushed an update to v0.1.1. If you update you should see the changes :)
