### ISSUE TITLE
command 'extension.createNewFile' not found

### ISSUE THREAD

**Issue by lengk** [dkundel/vscode-new-file#22]
Version 1.12.1 (1.12.1)
OSX: 10.12.4

I've set the shortcut

![ keybinds.json File](https://cloud.githubusercontent.com/assets/5440566/25926053/8210c0ae-35e4-11e7-9cb9-109e83978964.png)

However, I'm getting this error message:

![Error Message](https://cloud.githubusercontent.com/assets/5440566/25926048/7b6427aa-35e4-11e7-8784-1678330266a7.png)

**Comment by dkundel** [comment]
Hey @lengk I just published v3.0.0 of the extension and as part of that I switched the namespace of the command to `newFile.createNewFile`. Just update and change the keyboard shortcut to that and it should work :) Let me know if you encounter any problems.
