### ISSUE TITLE
Make extension work with workspaces

### ISSUE THREAD

**Issue by dkundel** [dkundel/vscode-new-file#29]
Right now the extension doesn't work with additional folders you might have loaded in your workspace. There are multiple solutions to this problem.

The idea that I have in my mind right now is a selection dialog that pops up when you trigger the extension to choose which sub-folder of the workspace you want to use as the basis. 

Happy to see other suggestions though.

**Comment by Telokis** [comment]
Disclaimer: Haven't used the multi-workspace stuff.

Couldn't you just determine the workspace from the current file?

**Comment by dkundel** [comment]
I haven't looked into the API yet if it's possible. To repro it you can follow the following steps:

1. Open a folder via Code
2. In the `File` menu pick `Add folder to Workspace....` and pick another folder.

When you use the extension with relative to project root it currently adds it always to the initial folder you added to the workspace rather than relative to the project root of the folder you are currently in.

Cheers,
Dominik

**Comment by Telokis** [comment]
Ok, now that 1.18.0 is out ([changelog](https://code.visualstudio.com/updates/v1_18)), we need to support this asap. They provided a [guide](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) but I haven't read it yet.

**Comment by dkundel** [comment]
Yep I agree. I'm currently at a row of conferences but I'll try to get this done tomorrow morning with the help of the guide.
