### ISSUE TITLE
Discussion: Add trailing commas where es5 supports it

### ISSUE THREAD

**Issue by Telokis** [dkundel/vscode-new-file#34]
[This page summarize pretty well the reason for using those](https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8)

Quick recap:

- Cleaner diffs: Having trailing commas removes a line from the diff when we add something inside the array/object.
- Easier copy/pasting: Don't bother adding/removing it yourself, it will always be there.

It's not a life-changer but I like that little quality of life as a part of my life!

Moreover, Prettier has a config option to automatically add them if needed!
(trailingComma: "none|es5|all")

**Comment by dkundel** [comment]
I'm fine with having it. Do you want to add it to the config?

Cheers,
Dominik
