### ISSUE TITLE
Disable warning notification on dismissing the action

### ISSUE THREAD

**Issue by nikitavoloboev** [dkundel/vscode-new-file#39]
This popover is really annoying when you want to make a new file but then change your mind. 

![2017-11-03 at 21 12](https://user-images.githubusercontent.com/6391776/32394004-f5a37480-c0db-11e7-8411-8282c83aa99a.png)

Please allow users to remove it. Thank you.

**Comment by dkundel** [comment]
Sorry this has been fixed already by @Telokis in #33 but I haven't had the time to push an update. If you update your extension this should be fixed now.

Cheers,
Dominik
