### ISSUE TITLE
after hitting enter nothing happens. 

### ISSUE THREAD

**Issue by a-eid** [dkundel/vscode-new-file#41]
I'm using a mac and everything working fine up until hitting enter to confirm.
it does nothing.

**Comment by Telokis** [comment]
Hey!
Thanks for reporting this issue but we need more details, please.
What is your VSCode version? Are you using multiple workspaces? Is your extension up to date?
What are you talking about when you say "hitting enter to confirm"? What are you confirming?

Thanks for providing details!

**Comment by a-eid** [comment]
@Telokis 

I'm on the latest version of vscode ` 1.18.1 ` ,
I just installed the extension so its up to date. 
there is no errors in the output tab (extensions selected). 
what do you mean multiple workspaces? . 
confirm as in I wrote the path and want to create the file create the file. 
hitting return/enter has no effect.

**Comment by Telokis** [comment]
It works perfectly well for me.
How do you open the path input box? Do you use the shortcut or right click on a file?
Are you sure you have the correct rights for the directory you use?
I don't have a mac so I can't test in your environment, sadly.

**Comment by dkundel** [comment]
Hey @a-eid do you have any custom settings or are you using the default settings?

**Comment by a-eid** [comment]
Just the recommended settings on the readme

**Comment by dkundel** [comment]
I'm unable to reproduce the issue. What is the path that you are trying? Is the resulting path a path for which you don't have permission to create a file for?
