### ISSUE TITLE
Can't install from VS Code repository

### ISSUE THREAD

**Issue by krzkaczor** [dkundel/vscode-new-file#43]
Hey, 
this is super weird but I can't install this extension from inside of the visual studio code (install extensions command). Installing other extensions works without any problems.

Can someone reproduce this issue?

Best,
KK

**Comment by dkundel** [comment]
Hey @krzkaczor,

Can you provide a bit more information? Which version from VS Code are you using and on which operating system are you?

Cheers,
Dominik

**Comment by krzkaczor** [comment]
Hey @dkundel ,

sorry for bothering you. I just tried again today and it worked. Maybe MS CDNs had worse day or something :D 

Best regards,
KK

**Comment by dkundel** [comment]
No problem! Happy to hear it works! 

Cheers,
Dominik
