### ISSUE TITLE
The extension contains the whole Visual Studio Code App

### ISSUE THREAD

**Issue by ngocphamm** [dkundel/vscode-new-file#44]
At first, I noticed that the it takes a long time to install the extension. Then this is what I found.

```
~/.v/extensions »  du -sh dkundel.vscode-new-file-4.0.0
290M    dkundel.vscode-new-file-4.0.0
~/.v/extensions »  cd dkundel.vscode-new-file-4.0.0
~/.v/e/dkundel.vscode-new-file-4.0.0 »  du -sh .vscode-test
286M    .vscode-test
~/.v/e/dkundel.vscode-new-file-4.0.0 »  ll .vscode-test
total 0
drwxr-xr-x   3 ngoc  staff   96 Dec 11 22:56 .
drwxr-xr-x  15 ngoc  staff  480 Dec 11 22:56 ..
drwxr-xr-x   3 ngoc  staff   96 Dec 11 22:56 Visual Studio Code.app
~/.v/e/dkundel.vscode-new-file-4.0.0 »
```

So basically it contains the whole Visuao Studio Code app itself!

Does anyone know the reason why?

**Comment by dkundel** [comment]
Oh that's a brilliant catch! VS Code tests download a version of VS Code to run the tests on. For some reason it's not in the ignore file. I'll update that!

**Comment by ngocphamm** [comment]
3.2 MB now. Looking good! 👍
