### ISSUE TITLE
Don't close extension when switching from VSCode to Chrome

### ISSUE THREAD

**Issue by deadcoder0904** [dkundel/vscode-new-file#46]
So I am not sure if this is VSCode issue or the extensions, but when I press `CMD+OPTION+N` it opens up input to select `FOLDER` structure then when I press `ENTER` it asks for filename. That's the time I switched from `VSCODE` to `CHROME` using `ALT+TAB` & the extension closed.

The expected behaviour is that the extension must stay at the point where it asks FILENAME & the actual behaviour is it closes. So not sure its VSCode problem or extension so check it out & let me know. I will post it in VSCode repo then if its VSCode limitation.

**Comment by Telokis** [comment]
I don't think this is an issue we can handle on our side. It's VSCode's fault, sadly! :(

**Comment by deadcoder0904** [comment]
Hey @Telokis the solution is quite simple. 

I think you must mention it in the `README` on VSCode page & Github page. 

Just need to set this `"workbench.quickOpen.closeOnFocusLost": false` in `User Settings`.

**Comment by dkundel** [comment]
Hey @deadcoder0904 feel free to open a PR for the README to add it to it and I'm happy to merge it :)

Cheers,
Dominik

**Comment by deadcoder0904** [comment]
Done #47
