### ISSUE TITLE
[Suggestions] Possible new features

### ISSUE THREAD

**Issue by pingshunhuangalex** [dkundel/vscode-new-file#48]
1. Combine new file feature with open file feature, open files if the path exists
2. Path Autocomplete (I know it's been requested many times, https://github.com/patbenatar/vscode-advanced-new-file)
3. Support all directories, not just from a project (e.g. if I type ~/test/, it should also work)
4. display file icons in autocomplete
![image](https://user-images.githubusercontent.com/17170199/37861071-1314da0e-2f86-11e8-9fed-8bdb43699f0e.png)

**Comment by dkundel** [comment]
Hi @pingshunhuangalex!

Thanks for the suggestions. Let me address them separately:
1. That's already happening. If you type in a path that exists it will open it.
2. The other extension is essentially doing a hack that I'm not too fond of. I'm happy to accept pull requests if someone really wants to add this using this hack. I am tracking some issues listed in #24 that request to add quick pick options to the InputBox. This seems more reasonable than a two step process.
3. This works as well already
4. VS Code has a very limited API so at the moment this is not possible. Sorry.

**Comment by pingshunhuangalex** [comment]
Thanks for the answer @dkundel
