### ISSUE TITLE
Writes full path when creating file

### ISSUE THREAD

**Issue by sjiamnocna** [dkundel/vscode-new-file#62]
When creating file using CTRL+ALT+N, I've got full path, which in some cases may be unreadable. Possible solution is to add option to use only short path relative to (root/home/project/file) option.

instead
> "/school/server/home/stud/abc/abcdstudent/Documents/test/src/components/car/car.jsx"

I'd appreciate just
> "src/components/car/car.jsx"

BTW. directory autocomplete will be also appreciated, but not necessary :)

**Comment by dkundel** [comment]
Hey @sjiamnocna :) 

This already exists as part of the existing configuration. It's just not enabled for legacy reasons. If you add the following entries to your `settings.json` it should work:

```json
{
  "newFile.relativeTo": "project", // "root" or "project"
  "newFile.showPathRelativeTo": "project", // "project" or "none"
}
```
