### ISSUE TITLE
Select only newFile without extension

### ISSUE THREAD

**Issue by DerAlbertCom** [dkundel/vscode-new-file#7]
I would like that on a creation of a new file only the newFile Part of the new filename is selected. Because of that it is possible to directly write the new name and don't rewrite the extension.

**Comment by dkundel** [comment]
Hi @DerAlbertCom, 

From what I see, there is currently no way to do this. Will close this issue for now, but I'll keep my eyes open.

Cheers,
Dominik

**Comment by Telokis** [comment]
I'd just like to point out that this issue will be fixed by https://github.com/dkundel/vscode-new-file/pull/27 !
