### ISSUE TITLE
Respect absolute path

### ISSUE THREAD

**Issue by sarbbottam** [dkundel/vscode-new-file#8]
and use the absolute path to the current selected directory as the default value/placeholder 

For example, `src` is the currently selected folder, once the prompt comes up, after pressing ⌥⌘N, there is no way to find out what is the currently selected folder.

However, if the absolute path to currently selected folder can be displayed in the prompt, it would be great.
![screen shot 2016-04-16 at 8 21 54 pm](https://cloud.githubusercontent.com/assets/949380/14584852/3eefd824-0411-11e6-9722-b283e77efd79.png)

**Comment by dkundel** [comment]
Hi @sarbbottam,

You can activate in the configuration now to see the absolute path by turning the respective flag on in `v2.0.0`. These are all configurations:

```js
{
  "newFile.defaultBaseFileName": "newFile",
  "newFile.relativeTo": "file", // "root" or "project"
  "newFile.defaultFileExtension": ".ts",
  "newFile.rootDirectory": "~",
  "newFile.showFullPath": true
}
```
